---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envirya-dev
  labels:
    app: envirya
spec:
  selector:
    matchLabels:
      run: envirya-dev
  replicas: 2
  template:
    metadata:
      labels:
        run: envirya-dev
    spec:
      containers:
      - name: envirya-dev
        image: priyankaverma/envirya:dev-v17
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: envirya-dev
  labels:
    run: envirya-dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    run: envirya-dev
